apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.appFullname }}-redis'
  namespace: '{{ .Values.appFullname }}'
  labels:
    app: '{{ .Values.appFullname }}'
    tier: redis
spec:
  replicas: {{ .Values.app.redis.replicaCount }}
  selector:
    matchLabels:
      app: '{{ .Values.appFullname }}-redis'
  template:
    metadata:
      labels:
        app: '{{ .Values.appFullname }}-redis'
    spec:
      containers:
      - name: frontend
        image: '{{ .Values.app.redis.container.repository }}:{{ .Values.app.redis.container.tag }}'
        ports:
        - containerPort: {{ .Values.app.redis.container.port }}
          name: redis
        resources:
          limits:
            cpu: '{{ .Values.app.redis.resources.limits.cpu }}'
            memory: '{{ .Values.app.redis.resources.limits.memory }}'
          requests:
            cpu: '{{ .Values.app.redis.resources.requests.cpu }}'
            memory: '{{ .Values.app.redis.resources.requests.memory }}'
---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.appFullname }}-redis-svc'
spec:
  ports:
  - port: {{ .Values.svc.redis.port }}
    targetPort: {{ .Values.svc.redis.targetPort }}
  selector:
    app: redis